관심 BM API 개발
Young-Flow/server pull request #26
Opened 2024-12-29 11:35 UTC by jeongmallro

## ⭐ Summary

> #13 

<br>

## 📌 Tasks

1. 관심 BM API 개발 (스크랩 on/off 토글 형식)

<br>

2024-12-29 11:56 UTC, lsh2613 requested changes

2024-12-29 11:56 UTC, lsh2613 commented on src/main/java/com/pitchain/service/MyBmService.java
> +    }
좋아요 취소 -> false
좋아요 -> true를 반환하는 것은 로직의 대한 성공 여부 판별이 힘들 것 같습니다

반환값 없이 void를 사용하고 controller에서는 CustomApiResponse.onSuccess()를 반환해주면 좋을 것 같아요

2024-12-29 12:30 UTC, jeongmallro commented on src/main/java/com/pitchain/service/MyBmService.java
> +    }
클라이언트에 관심 등록이 됐는지 안 됐는지를 알려줘야 하지 않나요?

2024-12-29 13:12 UTC, lsh2613 commented on src/main/java/com/pitchain/service/MyBmService.java
> +    }
CustomApiResponse.onSuccess()까지 성공적으로 마무리 됐다면 성공 코드가 반환될 것이고, 중간에 예외처리로 인해 마무리 되지 않았다면 Advice를 통해 CustomApiResponse.onFailure()가 반환됩니다

현재 반환되고 있는 값은 CustomApiResponse가 가지고 있는 T data 부분입니다

요청에 대한 성공 여부는 CustomApiResponse.isSuccess로 처리하고 있어요

2024-12-29 13:37 UTC, jeongmallro commented on src/main/java/com/pitchain/service/MyBmService.java
> +    }
아 저는 요청에 대한 성공 여부를 나타낸 게 아니라 관심 등록/해제 여부를 나타낸 것입니다. 현재 상태가 BM 관심 등록했는지 해제했는지 알려줘야 한다고 생각했는데 프론트에서는 따로 조회하니까 굳이 알려줄 필요가 없는 건가요? 그런데 생각해보니 변수명도 isToggled로 애매하게 지었네요..

2024-12-29 15:29 UTC, lsh2613 commented on src/main/java/com/pitchain/controller/MyBmController.java
> +    public CustomApiResponse toggleMyBm(@PathVariable("bmId") Long bmId,
toggleLike
toggleLikeMyBm
과 같은 메소드명이 더 명확한 의미를 가질 수 있을 것 같네요

2024-12-29 15:29 UTC, lsh2613 commented on src/main/java/com/pitchain/service/MyBmService.java
> +        if (isToggled(member, bm)) {
isToggled()보단 isLiked()가 더 괜찮을 것 같아요

2024-12-29 16:29 UTC, lsh2613 commented on src/main/java/com/pitchain/service/MyBmService.java
> +    }
등록을 할 때 반환값이 필요한지 여부는 기획과 프론트랑 어떻게 협업할지에 따라서 달라질 것 같아요
예를 들어, 게시글을 등록 후 해당 게시글 detail 페이지로 넘어가야 한다면 게시글 등록 api에서 게시글id를 반환해야 하겠지만, like 기능에서는 반환값이 없어도 무방해 보입니다

2024-12-30 03:21 UTC, lsh2613 approved these changes

2024-12-30 03:21 UTC, merged